### ISSUE TITLE
API rate limit issue when running multiple jobs

### ISSUE THREAD

**Issue by liangyongxiang** [dblock/create-a-github-issue#6]
I am running 40 jobs at the same time in action, each job runs dblock/create-a-github-issue.
And some of them will report an error: 
```
API rate limit exceeded for installation ID xxxx:
```

This is the crate-a-github-issue part of the action: 
```
    - uses: dblock/create-a-github-issue@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        update_existing: true
        search_existing: all
```

Full info: https://github.com/microcai/gentoo-zh/runs/5345190401?check_suite_focus=true
